/* 项目展示数据：换真图只改 thumb 扩展名；type 决定标签颜色（web 金 / ai 紫 / game 蓝） */
export const projects = [
  {
    no: "01",
    title: "Otto's Portfolio",
    type: "web",
    tech: ["Next.js", "React", "Tailwind v4", "MDX"],
    thumb: "/projects/portfolio.png",
    url: "https://ottokeigo.com",
  },
  {
    no: "02",
    title: "Oiko · Murex",
    type: "web",
    tech: ["Next.js 14", "TypeScript", "Tailwind", "Supabase"],
    thumb: "/projects/oiko.png",
    url: "https://oiko-murex.vercel.app",
  },
  {
    no: "03",
    title: "Health Quiz Funnel",
    type: "web",
    tech: ["Next.js 15", "TypeScript", "Tailwind v4", "Zustand"],
    thumb: "/projects/health-quiz.png",
    url: "https://health-quiz-funnel.vercel.app",
  },
  {
    no: "04",
    title: "同花顺 · 时序图表",
    type: "web",
    tech: ["React 18", "TypeScript", "Vite", "uPlot"],
    thumb: "/projects/tonghuashun.png",
    url: "https://github.com/OttoMa2002/tonghuashun1",
  },
  {
    no: "05",
    title: "AI 语音门卫",
    type: "ai",
    tech: ["Python", "Pipecat", "FastAPI", "PostgreSQL"],
    thumb: "/projects/whaletech.png",
    url: "https://github.com/OttoMa2002/whaletechtakehome",
  },
  {
    no: "06",
    title: "2D Game",
    type: "game",
    tech: ["Unity", "C#"],
    thumb: "/projects/game-2d.png",
    url: "https://ottoma.itch.io/finalproject",
  },
  {
    no: "07",
    title: "3D Game",
    type: "game",
    tech: ["Unity", "C#"],
    thumb: "/projects/game-3d.png",
    url: "https://ottoma.itch.io/451-final-project",
  },
]
